### PR TITLE
Update Roles.aspx file url

### PR DESCRIPTION
**Pull request by govindajindal**
Update Roles.aspx file url  when click on Roles button on N2 UI

### CODE REVIEW

**Comment by bherila** [comment]
Thank you @govindajindal

**Comment by govindajindal** [comment]
Please let me know, when the code updates will be available in .Net nuget package update and what will be the version number??

**Comment by bherila** [comment]
It will be the next version, probably some time this weekend I will have time to test & deploy it.

**Comment by bherila** [comment]
@govindajindal the packages are released now.

**Comment by govindajindal** [comment]
Hi, I have taken update of all nuget package except "N2CMS.ReusableParts" because I am getting dll issue on update of this. This issue is already posted here - https://github.com/n2cms/n2cms/issues/788.

But still I didn't get the code changes which I have done in my dotnet project and getting roles page loading issue.

Can you please check it.

**Comment by bherila** [comment]
Hi @govindajindal , if you can fix the nuget package definitions I am more than happy to accept another PR and release updated packages. 

My workflow is currently using VS 2017 and the projects and build scripts need to be updated to support VS 2017 ie #787 before I can become a useful developer on this project again. I do not have the expertise with msbuild to be able to fix #787 and until that issue is resolved I am blocked :(

Thanks,
Ben

**Comment by govindajindal** [comment]
I think this changes has not updated correctly on nuget becuase it is showing version 2.9.6.18 on github.

Can you please redeploy release 2.9.6.19 again on nuget and check this changes after deploy.

image

Thanks in Advance!!
Govinda Jindal

**Comment by bherila** [comment]
@govindajindal I didn't tag the commit, that's all Github shows. The .19 packages are pushed to nuget.

**Comment by bherila** [comment]
@govindajindal I might advise to uninstall & reinstall the N2CMS packages, it may fix the issue with the update for you.

**Pull request merged**
